trigger:
- main

stages:
  - stage: CI
    displayName: 'Build & Test'
    jobs:
      - job: build
        displayName: 'Install, Test & Build'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - script: npm install
            displayName: 'Install dependencies'

          - script: npm test --if-present
            displayName: 'Run tests'

          - script: npm run build
            displayName: 'Build React app'

          # Publish build artifacts for deployment
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: 'build'
              artifactName: 'frontend-build'
              publishLocation: 'Container'

  - stage: CD
    displayName: 'Deploy'
    dependsOn: CI
    jobs:
      - job: deploy
        displayName: 'Deploy React App'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - download: current
            artifact: frontend-build

          - script: |
              echo "Deploying React app..."
              # Example: copy files to server
              # scp -r build/* user@server:/var/www/html/
            displayName: 'Deploy to Server'
